title: Multimedia Deadlines # (Maintained by @lidq92)
# email: dingquanli@pku.edu.cn
description: Countdown timers to keep track of conference deadlines that are related to multimedia (MM).
author: Dingquan Li


domain: lidq92.github.io
baseurl: 

github_username: lidq92
github_repo: lidq92.github.io

markdown: kramdown
ga_id: UA-36274081-2

theme: jekyll-theme-cayman